name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Laboratorios/Lab_02/**'

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Laboratorios/Lab_02

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Run Tests
        run: mvn -B test
